#!/usr/bin/env python3
"""
`redesign/fixtures/fixture_3day.html` must not be used for acceptance.

    python verify/check_fixture_quarantine.py

It is the only fixture exercising the three-day case, and it is epk's payload
wearing bordeaux's day names: bordeaux day names, dates and capacities, with
epk's `presdays` aggregates, epk's `comp` block copied identically across all
three days, a `jeudi` reference of 1 640 against a `bordeaux_2025` that has no
Jeudi, and a `projx.cands` keyed `epk_2023` with September dates.

`presdays.days` sums to 34 266 while `presdays.paid` says 10 039. It is not
consistent with itself, let alone with any event.

WHY A CHECK RATHER THAN A NOTE
------------------------------
§6 requires all four fixtures to render clean and §7's assertions run against
them. This one would **pass** — no NaN, no undefined, no horizontal scroll —
while encoding both the withdrawn default total and the forward day mapping that
§5.6 rules out. A green acceptance run would mean nothing for the three-day
case, and would say so nowhere. That is START_HERE §5's "a check can pass for
the wrong reason" sitting inside the acceptance criteria itself.

So the quarantine is enforced, not documented. This fails while the fixture
still carries epk's fingerprints, and passes once it is regenerated by
`dashboard_payload.py` to the figures in `redesign/FIXTURE_3DAY_TARGET.md`.

Repairing it by hand is not regeneration. Hand-authoring a payload from partly
real figures is how this file came to exist.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FIXTURE = ROOT / 'redesign' / 'fixtures' / 'fixture_3day.html'

# Each marker is a fact about the fixture that cannot be true of bordeaux.
MARKERS = [
    ('epk_2023 as the projection candidate', r'"epk_2023"\s*:'),
    ('"EPK 2023" as the candidate label', r'EPK 2023'),
    ('September dates on a June event', r'"2026-09-\d\d"'),
    ('epk presdays.paid (10039)', r'"paid"\s*:\s*10039'),
    ('the withdrawn jeudi total (1916)', r'"now"\s*:\s*1916'),
    ('a jeudi reference (1640) with no reference Jeudi', r'"ref"\s*:\s*1640'),
]

# Bordeaux's real figures, from FIXTURE_3DAY_TARGET.md. Presence only - the
# regenerated fixture must carry these three.
REQUIRED = [('jeudi now', 5979), ('vendredi now', 15416), ('samedi now', 19388)]


def main():
    if not FIXTURE.exists():
        print(f'FAIL: {FIXTURE} is missing.')
        print('      Deleting the fixture is not regenerating it - the three-day')
        print('      case then has no coverage at all.')
        return 1
    html = FIXTURE.read_text(encoding='utf-8')

    found = [(label, pat) for label, pat in MARKERS if re.search(pat, html)]
    print(f'epk fingerprints in {FIXTURE.relative_to(ROOT)}:')
    for label, _ in MARKERS:
        hit = any(label == f[0] for f in found)
        print(f'  {"PRESENT" if hit else "gone   "}  {label}')

    print('\nbordeaux presence figures required by FIXTURE_3DAY_TARGET.md:')
    missing = []
    for label, value in REQUIRED:
        ok = re.search(rf'"now"\s*:\s*{value}\b', html) is not None
        print(f'  {"ok     " if ok else "MISSING"}  {label} = {value}')
        if not ok:
            missing.append(label)

    print()
    if found or missing:
        print(f'QUARANTINED: {len(found)} epk fingerprint(s), '
              f'{len(missing)} required figure(s) missing.')
        print('A §7 acceptance run including this fixture proves nothing about')
        print('the three-day case. Regenerate via dashboard_payload.py; do not')
        print('repair by hand.')
        return 1
    print('fixture_3day carries no epk fingerprints and matches the target '
          'figures - quarantine lifted')
    return 0


if __name__ == '__main__':
    sys.exit(main())
